### ISSUE TITLE
rustplus.config.json dont exist in root folder

### ISSUE THREAD

**Issue by leopaoca13** [alexemanuelol/RustPlus-Discord-Bot#4]
The error:
`[ERROR] rustplus.config.json file does not exist inside root folder.
 Try running the command: 'npx @liamcottle/rustplus.js fcm-register' and then place the output 'rustplus.config.json' file in the root folder of the RustPlus-Discord-Bot.`

what I tried to run
`node tools/external/copy_server_details_to_config.js`

I have rustplus.config.json in my root folder.

**Comment by elightcap** [comment]
I know its closed, and thank you for putting this, but maybe it should be added to the readme.  First place i looked was here of course, but other people who might not be as familiar with git may not check issues.

**Comment by alexemanuelol** [comment]
@elightcap You are correct, I will do it. Have lost focus on this project, currently working on version 2 ^^
https://github.com/alexemanuelol/rustPlusPlus

**Comment by elightcap** [comment]
@alexemanuelol oh awsesome, cant wait to check that out
