### ISSUE TITLE
Commands from Discord Bots

### ISSUE THREAD

**Issue by mtvProof** [alexemanuelol/RustPlus-Discord-Bot#5]
I’ve been using your discord Rust Plus with my group for the past two weeks or so and we really enjoy it, just wondering if it is possible to allow your discord bot to take commands from another discord bot? I have my streamdeck set up using webhooks so when i push a button a webhook bot will say “!turnOn turrets” in the correct channel, but your bot ignores it since it is coming from a discord bot, is this something I could easily change? or maybe in a future update?

Thanks

**Comment by alexemanuelol** [comment]
Hello,

It would be possible to change but from what I understand, that's against Discord ToS and may result in an account ban.

**Comment by mtvProof** [comment]
Which part is against the discord ToS? I haven't looked into it, but I wouldnt think using webhooks to control a discord bot would be against the ToS

**Comment by alexemanuelol** [comment]
Just a quick search gave me several sources saying that it's bad practice responding to other bot commands. It could be interpreted as spam, endless loop, etc... which would be against the ToS.

Here are just some of the sources I found:
https://stackoverflow.com/questions/56799778/discord-bot-to-trigger-other-bots-actions
https://www.reddit.com/r/discordapp/comments/a35txa/bots_setting_other_bots_commands/
