### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Nou4r** [alexemanuelol/RustPlus-Discord-Bot#6]
Here is my suggestion to enhance the experience with the bot:

1. Enable/Disable Switch with Reactions
![image](https://user-images.githubusercontent.com/12816677/150352149-0d61cb43-701f-473d-8422-e08391cf20d5.png)

2. Show contents of Vending Machine/Large Box via images portraying the respective item.
3. Show connected TC Upkeep
![image](https://user-images.githubusercontent.com/12816677/150352723-07b87565-0353-41b9-9b59-9a6b2755fcab.png)

4. Show Server Information
![image](https://user-images.githubusercontent.com/12816677/150352680-8b1ac6c1-05f0-4064-93de-9c7ab3f0053b.png)

**Comment by alexemanuelol** [comment]
Yea I have some of those changes in mind with the new bot Im currently working on :)
https://github.com/alexemanuelol/rustPlusPlus
